name: Hybrid CSE Workflow

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-performance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@4

      - name: Set up Python
        uses: actions/setup-python@5
        with: 
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run Unit and Integration tests
        run: |
          poetry run pytest

      - name: Build and run Docker container
        run: |
          docker build -t hybrid-cse-api .
          docker run -d -p 8000:8000 hybrid-cse-api

      - name: Wait for API
        run: |
          sleep 5
          curl --fail http://localhost:8000/heath

      - name: Run Locust
        run: |
          poetry run locust -f tests/performance/locustfile.py \
          --host=http://localhost:8000 \
          --users 20 \
          --spawn-rate 5 \
          --run-time 30s \
          --headless
